/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _landingRouteImport } from './routes/__landing'
import { Route as _adminRouteImport } from './routes/__admin'
import { Route as _landingIndexRouteImport } from './routes/__landing/index'
import { Route as _landingContactRouteImport } from './routes/__landing/contact'
import { Route as _landingBlogRouteImport } from './routes/__landing/blog'
import { Route as _authSignupRouteImport } from './routes/__auth/signup'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _adminAdminIndexRouteImport } from './routes/__admin/admin/index'
import { Route as _adminAdminProductsRouteImport } from './routes/__admin/admin/products'
import { Route as _adminAdminProductTableRouteImport } from './routes/__admin/admin/ProductTable'

const _landingRoute = _landingRouteImport.update({
  id: '/__landing',
  getParentRoute: () => rootRouteImport,
} as any)
const _adminRoute = _adminRouteImport.update({
  id: '/__admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _landingIndexRoute = _landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _landingRoute,
} as any)
const _landingContactRoute = _landingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => _landingRoute,
} as any)
const _landingBlogRoute = _landingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => _landingRoute,
} as any)
const _authSignupRoute = _authSignupRouteImport.update({
  id: '/__auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/__auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _adminAdminIndexRoute = _adminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => _adminRoute,
} as any)
const _adminAdminProductsRoute = _adminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => _adminRoute,
} as any)
const _adminAdminProductTableRoute = _adminAdminProductTableRouteImport.update({
  id: '/admin/ProductTable',
  path: '/admin/ProductTable',
  getParentRoute: () => _adminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof _authLoginRoute
  '/signup': typeof _authSignupRoute
  '/blog': typeof _landingBlogRoute
  '/contact': typeof _landingContactRoute
  '/': typeof _landingIndexRoute
  '/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/admin/products': typeof _adminAdminProductsRoute
  '/admin': typeof _adminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof _authLoginRoute
  '/signup': typeof _authSignupRoute
  '/blog': typeof _landingBlogRoute
  '/contact': typeof _landingContactRoute
  '/': typeof _landingIndexRoute
  '/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/admin/products': typeof _adminAdminProductsRoute
  '/admin': typeof _adminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__admin': typeof _adminRouteWithChildren
  '/__landing': typeof _landingRouteWithChildren
  '/__auth/login': typeof _authLoginRoute
  '/__auth/signup': typeof _authSignupRoute
  '/__landing/blog': typeof _landingBlogRoute
  '/__landing/contact': typeof _landingContactRoute
  '/__landing/': typeof _landingIndexRoute
  '/__admin/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/__admin/admin/products': typeof _adminAdminProductsRoute
  '/__admin/admin/': typeof _adminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/blog'
    | '/contact'
    | '/'
    | '/admin/ProductTable'
    | '/admin/products'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/blog'
    | '/contact'
    | '/'
    | '/admin/ProductTable'
    | '/admin/products'
    | '/admin'
  id:
    | '__root__'
    | '/__admin'
    | '/__landing'
    | '/__auth/login'
    | '/__auth/signup'
    | '/__landing/blog'
    | '/__landing/contact'
    | '/__landing/'
    | '/__admin/admin/ProductTable'
    | '/__admin/admin/products'
    | '/__admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _adminRoute: typeof _adminRouteWithChildren
  _landingRoute: typeof _landingRouteWithChildren
  _authLoginRoute: typeof _authLoginRoute
  _authSignupRoute: typeof _authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__landing': {
      id: '/__landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _landingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__admin': {
      id: '/__admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__landing/': {
      id: '/__landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _landingIndexRouteImport
      parentRoute: typeof _landingRoute
    }
    '/__landing/contact': {
      id: '/__landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof _landingContactRouteImport
      parentRoute: typeof _landingRoute
    }
    '/__landing/blog': {
      id: '/__landing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof _landingBlogRouteImport
      parentRoute: typeof _landingRoute
    }
    '/__auth/signup': {
      id: '/__auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof _authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__admin/admin/': {
      id: '/__admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof _adminAdminIndexRouteImport
      parentRoute: typeof _adminRoute
    }
    '/__admin/admin/products': {
      id: '/__admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof _adminAdminProductsRouteImport
      parentRoute: typeof _adminRoute
    }
    '/__admin/admin/ProductTable': {
      id: '/__admin/admin/ProductTable'
      path: '/admin/ProductTable'
      fullPath: '/admin/ProductTable'
      preLoaderRoute: typeof _adminAdminProductTableRouteImport
      parentRoute: typeof _adminRoute
    }
  }
}

interface _adminRouteChildren {
  _adminAdminProductTableRoute: typeof _adminAdminProductTableRoute
  _adminAdminProductsRoute: typeof _adminAdminProductsRoute
  _adminAdminIndexRoute: typeof _adminAdminIndexRoute
}

const _adminRouteChildren: _adminRouteChildren = {
  _adminAdminProductTableRoute: _adminAdminProductTableRoute,
  _adminAdminProductsRoute: _adminAdminProductsRoute,
  _adminAdminIndexRoute: _adminAdminIndexRoute,
}

const _adminRouteWithChildren =
  _adminRoute._addFileChildren(_adminRouteChildren)

interface _landingRouteChildren {
  _landingBlogRoute: typeof _landingBlogRoute
  _landingContactRoute: typeof _landingContactRoute
  _landingIndexRoute: typeof _landingIndexRoute
}

const _landingRouteChildren: _landingRouteChildren = {
  _landingBlogRoute: _landingBlogRoute,
  _landingContactRoute: _landingContactRoute,
  _landingIndexRoute: _landingIndexRoute,
}

const _landingRouteWithChildren = _landingRoute._addFileChildren(
  _landingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _adminRoute: _adminRouteWithChildren,
  _landingRoute: _landingRouteWithChildren,
  _authLoginRoute: _authLoginRoute,
  _authSignupRoute: _authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
