/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as _adminRouteImport } from './routes/__admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _adminAdminIndexRouteImport } from './routes/__admin/admin/index'
import { Route as _adminAdminProductsRouteImport } from './routes/__admin/admin/products'
import { Route as _adminAdminProductTableRouteImport } from './routes/__admin/admin/ProductTable'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const _adminRoute = _adminRouteImport.update({
  id: '/__admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _adminAdminIndexRoute = _adminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => _adminRoute,
} as any)
const _adminAdminProductsRoute = _adminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => _adminRoute,
} as any)
const _adminAdminProductTableRoute = _adminAdminProductTableRouteImport.update({
  id: '/admin/ProductTable',
  path: '/admin/ProductTable',
  getParentRoute: () => _adminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/admin/products': typeof _adminAdminProductsRoute
  '/admin': typeof _adminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/admin/products': typeof _adminAdminProductsRoute
  '/admin': typeof _adminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__admin': typeof _adminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/__admin/admin/ProductTable': typeof _adminAdminProductTableRoute
  '/__admin/admin/products': typeof _adminAdminProductsRoute
  '/__admin/admin/': typeof _adminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/login'
    | '/signup'
    | '/admin/ProductTable'
    | '/admin/products'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/login'
    | '/signup'
    | '/admin/ProductTable'
    | '/admin/products'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/__admin'
    | '/blog'
    | '/contact'
    | '/login'
    | '/signup'
    | '/__admin/admin/ProductTable'
    | '/__admin/admin/products'
    | '/__admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _adminRoute: typeof _adminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__admin': {
      id: '/__admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__admin/admin/': {
      id: '/__admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof _adminAdminIndexRouteImport
      parentRoute: typeof _adminRoute
    }
    '/__admin/admin/products': {
      id: '/__admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof _adminAdminProductsRouteImport
      parentRoute: typeof _adminRoute
    }
    '/__admin/admin/ProductTable': {
      id: '/__admin/admin/ProductTable'
      path: '/admin/ProductTable'
      fullPath: '/admin/ProductTable'
      preLoaderRoute: typeof _adminAdminProductTableRouteImport
      parentRoute: typeof _adminRoute
    }
  }
}

interface _adminRouteChildren {
  _adminAdminProductTableRoute: typeof _adminAdminProductTableRoute
  _adminAdminProductsRoute: typeof _adminAdminProductsRoute
  _adminAdminIndexRoute: typeof _adminAdminIndexRoute
}

const _adminRouteChildren: _adminRouteChildren = {
  _adminAdminProductTableRoute: _adminAdminProductTableRoute,
  _adminAdminProductsRoute: _adminAdminProductsRoute,
  _adminAdminIndexRoute: _adminAdminIndexRoute,
}

const _adminRouteWithChildren =
  _adminRoute._addFileChildren(_adminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _adminRoute: _adminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
